---
# template: 1.1.0
name: "SAST/GitLeaks"

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "feature/**"

jobs:
  sast-gitleaks:
    uses: "automation64/github-workflow-gitleaks/.github/workflows/main.yaml@main"
    with:
      DEV_CICD_DEBUG: "${{ vars.DEV_CICD_DEBUG }}"
...
